package MemorIA.dto;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * DTO complet pour la réponse d'une alerte individuelle
 * Inclut le score de gravité dynamique et explications IA
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AlertResponseDTO {

    /**
     * === IDENTIFIANTS ===
     */

    @JsonProperty("id")
    private Long id;

    @JsonProperty("patient_id")
    private Long patientId;

    @JsonProperty("patient_name")
    private String patientName;

    /**
     * === CONTENU DE L'ALERTE ===
     */

    @JsonProperty("type")
    private String type;

    @JsonProperty("title")
    private String title;

    @JsonProperty("description")
    private String description;

    @JsonProperty("severity")
    private String severity;

    @JsonProperty("status")
    private String status;

    /**
     * === SCORE DE GRAVITÉ DYNAMIQUE ===
     */

    /**
     * Score de gravité calculé (0-100)
     * Basé sur: type, urgence, historique patient, patterns détectés
     */
    @JsonProperty("gravity_score")
    private Integer gravityScore;

    /**
     * Explications textuelles du score (ex: "High due to 5 missed medications + cognitive decline pattern")
     */
    @JsonProperty("gravity_explanation")
    private String gravityExplanation;

    /**
     * Couleur d'affichage calculée depuis le gravityScore
     * RED (gravityScore >= 70), ORANGE (40-69), YELLOW (20-39), GREEN (< 20)
     */
    @JsonProperty("color")
    private String color;

    /**
     * Alerte critique - affiche clignotement dans frontend
     * true si gravityScore >= 70 ou severity == CRITICAL
     */
    @JsonProperty("is_critical")
    private Boolean isCritical;

    /**
     * === PROPRIÉTÉS MÉTIER ===
     */

    @JsonProperty("is_read")
    private Boolean isRead;

    @JsonProperty("is_escalated")
    private Boolean isEscalated;

    @JsonProperty("is_auto_generated")
    private Boolean isAutoGenerated;

    /**
     * === RELATIONS ===
     */

    @JsonProperty("created_by_id")
    private Long createdById;

    @JsonProperty("created_by_name")
    private String createdByName;

    @JsonProperty("created_by_role")
    private String createdByRole;

    @JsonProperty("assigned_to_user_id")
    private Long assignedToUserId;

    @JsonProperty("assigned_to_user_name")
    private String assignedToUserName;

    @JsonProperty("resolved_by_user_id")
    private Long resolvedById;

    @JsonProperty("resolved_by_user_name")
    private String resolvedByName;

    /**
     * Lien vers reminder source (si créée depuis reminder manqué)
     */
    @JsonProperty("linked_reminder_id")
    private Long linkedReminderId;

    /**
     * === TIMESTAMPS ===
     */

    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
    @JsonProperty("created_at")
    private LocalDateTime createdAt;

    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
    @JsonProperty("assigned_at")
    private LocalDateTime assignedAt;

    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
    @JsonProperty("resolved_at")
    private LocalDateTime resolvedAt;

    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
    @JsonProperty("updated_at")
    private LocalDateTime updatedAt;

    /**
     * === NOTES CLINIQUES ===
     */

    @JsonProperty("clinical_note")
    private String clinicalNote;

    /**
     * === SOURCE ===
     */

    @JsonProperty("source_key")
    private String sourceKey;
}
