package MemorIA.dto;

import MemorIA.entity.alerts.Alert;
import MemorIA.entity.alerts.AlertType;

import java.time.LocalDateTime;

public record AlertDTO(
        Long id,
        Long patientId,
        String patientName,
        String title,
        String description,
        AlertType type,
        Alert.AlertStatus status,
        Alert.AlertSeverity severity,
        LocalDateTime createdAt,
        LocalDateTime updatedAt,
        LocalDateTime assignedAt,
        LocalDateTime resolvedAt,
        boolean read,
        Long createdById,
        String createdByName,
        Long assignedToUserId,
        String assignedToUserName,
        Long resolvedByUserId,
        String resolvedByUserName,
        Long reminderId,
        boolean autoGenerated,
        Integer gravityScore,         // ✨ Nouveau
        String gravityExplanation,    // ✨ Nouveau
        String color,                 // ✨ Nouveau (RED, ORANGE, YELLOW, GREEN)
        Boolean isCritical,           // ✨ Nouveau
        String clinicalNote           // Notes cliniques visibles dans les listes d'alertes
) {
}
