package MemorIA.dto;

import MemorIA.entity.alerts.Alert;
import MemorIA.entity.alerts.AlertType;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.LocalDateTime;

/**
 * DTO for alerts displayed to caregivers
 * Includes gravity scoring and alert status
 */
public record CaregiverAlertDTO(
        @JsonProperty("id")
        Long id,

        @JsonProperty("patient_id")
        Long patientId,

        @JsonProperty("patient_name")
        String patientName,

        @JsonProperty("type")
        AlertType type,

        @JsonProperty("title")
        String title,

        @JsonProperty("description")
        String description,

        @JsonProperty("severity")
        Alert.AlertSeverity severity,

        @JsonProperty("status")
        Alert.AlertStatus status,

        @JsonProperty("is_read")
        boolean read,

        @JsonProperty("created_at")
        LocalDateTime createdAt,

        @JsonProperty("created_by_role")
        String createdByRole,

        @JsonProperty("gravity_score")
        Integer gravityScore,

        @JsonProperty("gravity_explanation")
        String gravityExplanation,

        @JsonProperty("color")
        String color,

        @JsonProperty("is_critical")
        Boolean isCritical,

        @JsonProperty("is_auto_generated")
        boolean autoGenerated
) {
}
