package MemorIA.dto;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * DTO for weather alert response - includes all details about a generated weather alert
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class WeatherAlertResponseDTO {

    @JsonProperty("id")
    private Long id;

    @JsonProperty("patient_id")
    private Long patientId;

    @JsonProperty("patient_name")
    private String patientName;

    @JsonProperty("title")
    private String title;

    @JsonProperty("description")
    private String description;

    @JsonProperty("severity")
    private String severity;

    @JsonProperty("status")
    private String status;

    @JsonProperty("type")
    private String type;

    @JsonProperty("weather_condition")
    private String weatherCondition;

    @JsonProperty("temperature")
    private Double temperature;

    @JsonProperty("wind_speed")
    private Double windSpeed;

    @JsonProperty("precipitation")
    private Double precipitation;

    @JsonProperty("recommendation")
    private String recommendation;

    @JsonProperty("is_read")
    private Boolean isRead;

    @JsonProperty("is_critical")
    private Boolean isCritical;

    @JsonProperty("gravity_score")
    private Integer gravityScore;

    @JsonProperty("auto_generated")
    private Boolean autoGenerated;

    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
    @JsonProperty("created_at")
    private LocalDateTime createdAt;

    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
    @JsonProperty("updated_at")
    private LocalDateTime updatedAt;
}
