package MemorIA.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO for creating weather-related alerts manually or via scheduling
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class WeatherAlertRequestDTO {

    @JsonProperty("patient_id")
    private Long patientId;

    @JsonProperty("title")
    private String title;

    @JsonProperty("description")
    private String description;

    @JsonProperty("severity")
    private String severity; // LOW, MEDIUM, HIGH, CRITICAL

    @JsonProperty("weather_condition")
    private String weatherCondition; // HEAVY_RAIN, STORM, EXTREME_HEAT, EXTREME_COLD, STRONG_WIND, etc.

    @JsonProperty("temperature")
    private Double temperature;

    @JsonProperty("wind_speed")
    private Double windSpeed;

    @JsonProperty("precipitation")
    private Double precipitation;

    @JsonProperty("recommendation")
    private String recommendation;

    @JsonProperty("auto_generated")
    private Boolean autoGenerated = true;
}
