package MemorIA.entity.alerts;

import MemorIA.entity.Patient;
import MemorIA.entity.User;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

@Entity
@Table(
        name = "alerts",
        indexes = {
                @Index(name = "idx_alerts_patient", columnList = "patient_id"),
                @Index(name = "idx_alerts_created_at", columnList = "created_at"),
                @Index(name = "idx_alerts_status", columnList = "status")
        }
)
@Getter
@Setter
public class Alert {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "patient_id", nullable = false)
    private Patient patient;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by_id")
    private User createdBy;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "assigned_to_user_id")
    private User assignedToUser;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "resolved_by_user_id")
    private User resolvedByUser;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 40)
    private AlertType type;

    @Column(nullable = false, length = 180)
    private String title;

    @Column(nullable = false, length = 1200)
    private String description;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private AlertStatus status;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private AlertSeverity severity;

    @Column(name = "is_read", nullable = false)
    private boolean read;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @Column(name = "assigned_at")
    private LocalDateTime assignedAt;

    @Column(name = "resolved_at")
    private LocalDateTime resolvedAt;

    @Column(name = "reminder_id")
    private Long reminderId;

    @Column(name = "source_key", length = 120)
    private String sourceKey;

    @Column(name = "is_auto_generated", nullable = false)
    private boolean autoGenerated;

    /**
     * Score de gravité dynamique (0-100)
     * Calculé selon règles métier:
     * +40 si reminder manqué, +30 si critique, +15 par oubli médicament,
     * +10 par baisse activité, etc.
     */
    @Column(name = "gravity_score", nullable = false)
    private Integer gravityScore = 0;

    /**
     * Indicateur d'escalade - alerte escaladée ou non
     */
    @Column(name = "is_escalated", nullable = false)
    private boolean escalated = false;

    /**
     * Alerte critique - nécessite attention urgente et clignotement frontend
     * Déterminé par calculateGravityScore si gravityScore >= 70 ou severity == CRITICAL
     */
    @Column(name = "is_critical", nullable = false)
    private boolean critical = false;

    /**
     * Lien vers le reminder original (si créée depuis reminder manqué)
     * Permet de tracer l'alerte jusqu'à sa source et éviter les doublons
     */
    @Column(name = "linked_reminder_id")
    private Long linkedReminderId;

    /**
     * Note clinique libre ajoutée par le professionnel
     */
    @Column(name = "clinical_note", length = 2000)
    private String clinicalNote;

    @PrePersist
    void onCreate() {
        LocalDateTime now = LocalDateTime.now();
        createdAt = now;
        updatedAt = now;

        if (status == null) {
            status = AlertStatus.UNREAD;
        }
        if (severity == null) {
            severity = AlertSeverity.MEDIUM;
        }

        if (assignedToUser != null && assignedAt == null) {
            assignedAt = now;
        }

        if (status == AlertStatus.RESOLVED) {
            read = true;
            if (resolvedAt == null) {
                resolvedAt = now;
            }
        }
        if (sourceKey == null && reminderId != null) {
            sourceKey = "REMINDER_MISSED:" + reminderId;
        }
    }

    @PreUpdate
    void onUpdate() {
        updatedAt = LocalDateTime.now();

        if (assignedToUser != null && assignedAt == null) {
            assignedAt = updatedAt;
        }

        if (status == AlertStatus.RESOLVED) {
            read = true;
            if (resolvedAt == null) {
                resolvedAt = updatedAt;
            }
        }
    }

    public enum AlertStatus {
        // English values
        UNREAD,
        IN_PROGRESS,
        RESOLVED,
        // Legacy French values kept for DB compatibility
        NOUVELLE,
        PRISE_EN_CHARGE,
        RESOLUE
    }

    public enum AlertSeverity {
        // English values
        LOW,
        MEDIUM,
        HIGH,
        CRITICAL,
        // Legacy French values kept for DB compatibility
        FAIBLE,
        MOYEN,
        ELEVE,
        CRITIQUE
    }
}
