package MemorIA.service.impl;

import MemorIA.dto.AlertResponseDTO;
import MemorIA.dto.ManualAlertRequestDTO;
import MemorIA.entity.CaregiverLink;
import MemorIA.entity.Patient;
import MemorIA.entity.User;
import MemorIA.entity.alerts.Alert;
import MemorIA.entity.alerts.Alert.AlertSeverity;
import MemorIA.entity.alerts.Alert.AlertStatus;
import MemorIA.entity.alerts.AlertType;
import MemorIA.repository.*;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

/**
 * Service pour la gestion les tâches liées aux alertes pour l'accompagnant
 * 
 * Responsabilités:
 * - Créer des alertes manuelles (accompagnant, médecin)
 * - Récupérer TOUTES les alertes d'un patient (sans restriction de créateur)
 * - Marquer alerte comme "en cours de traitement"
 * - Résoudre une alerte
 * - Ajouter des notes cliniques
 * - Vérifier le lien CaregiverLink avant autoriser les actions
 *
 * Règles métier:
 * - Un accompagnant ne peut créer/modifier alertes que pour ses patients liés
 * - Un médecin peut créer/modifier pour tous ses patients
 * - Les alertes manuelles ont "isAutoGenerated = false" et "createdByRole" stockée
 */
@Service
@Slf4j
@RequiredArgsConstructor
@Transactional
public class CaregiverAlertService {

    private final AlertRepository alertRepository;
    private final CaregiverLinkRepository caregiverLinkRepository;
    private final PatientRepository patientRepository;
    private final UserRepository userRepository;

    /**
     * Crée une alerte manuelle
     * 
     * @param request Contient: patientId, type, title, description, severity, dateTime, notifyDoctor
     * @param userId ID de l'utilisateur qui crée l'alerte
     * @param userRole Rôle de l'utilisateur (CAREGIVER, DOCTOR, SOIGNANT)
     * @return Alert créée
     * @throws ResponseStatusException si le caregiver n'est pas lié au patient (403)
     */
    public Alert createManualAlert(ManualAlertRequestDTO request, Long userId, String userRole) {
        log.info("[CaregiverAlertService] Creating manual alert for patient {} by {} ({})",
                request.patientId(), userId, userRole);

        // Vérifier que le patient existe
        Patient patient = patientRepository.findById(request.patientId())
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, 
                    "Patient not found"));

        // Vérifier les droits: accompagnant doit être lié au patient
        if ("CAREGIVER".equalsIgnoreCase(userRole)) {
            verifyAccessToPatient(userId, request.patientId());
        }

        // Récupérer l'utilisateur qui crée
        User createdBy = userRepository.findById(userId)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND,
                    "User not found"));

        // Créer l'alerte
        Alert alert = new Alert();
        alert.setPatient(patient);
        alert.setCreatedBy(createdBy);
        alert.setType(request.type());
        alert.setTitle(request.title());
        alert.setDescription(request.description());
        alert.setSeverity(request.severity());
        alert.setStatus(AlertStatus.UNREAD);
        alert.setRead(false);
        alert.setAutoGenerated(false);  // Alerte manuelle
        alert.setEscalated(false);
        
        // Calculer le gravity score selon la sévérité
        alert.setGravityScore(calculateGravityScore(alert));

        // Sauvegarder
        Alert saved = alertRepository.save(alert);
        log.info("[CaregiverAlertService] Manual alert created: id={}, patient={}", 
            saved.getId(), patient.getId());

        // TODO: Si notifyDoctor=true, envoyer une notification au médecin assigné du patient

        return saved;
    }

    /**
     * Récupère TOUTES les alertes d'un patient
     * - Für caregiver: doit être lié au patient
     * - Für doctor: peut voir tous les patients
     * 
     * @param patientId ID du patient
     * @param userId ID de l'utilisateur
     * @param userRole Rôle (CAREGIVER, DOCTOR, SOIGNANT)
     * @return Liste de toutes les alertes du patient triées par date décroissante
     */
    @Transactional(readOnly = true)
    public List<AlertResponseDTO> getAlertsForPatient(Long patientId, Long userId, String userRole) {
        log.info("[CaregiverAlertService] Getting all alerts for patient {} by {} ({})",
                patientId, userId, userRole);

        // Vérifier les droits
        if ("CAREGIVER".equalsIgnoreCase(userRole)) {
            verifyAccessToPatient(userId, patientId);
        }

        // Récupérer TOUTES les alertes du patient (pas de filtre sur créateur)
        List<Alert> alerts = alertRepository.findByPatientIdOrderByCreatedAtDesc(patientId);

        return alerts.stream()
                .map(this::mapToResponseDTO)
                .toList();
    }

    /**
     * Marque une alerte comme "en cours de traitement"
     * 
     * @param alertId ID de l'alerte
     * @param userId ID de l'utilisateur (caregiver/doctor)
     * @param userRole Rôle de l'utilisateur
     * @throws ResponseStatusException si alerte pas trouvée (404), accès refusé (403), ou déjà résolue (409)
     */
    public void takeInChargeAlert(Long alertId, Long userId, String userRole) {
        log.info("[CaregiverAlertService] Taking charge of alert {} by {} ({})",
                alertId, userId, userRole);

        Alert alert = alertRepository.findById(alertId)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND,
                    "Alert not found"));

        // Vérifier les droits d'accès au patient
        if ("CAREGIVER".equalsIgnoreCase(userRole)) {
            verifyAccessToPatient(userId, alert.getPatient().getId());
        }

        // Vérifier que l'alerte n'est pas déjà résolue
        if (AlertStatus.RESOLVED.equals(alert.getStatus())) {
            throw new ResponseStatusException(HttpStatus.CONFLICT,
                "Cannot take charge of already resolved alert");
        }

        // Mettre à jour
        User assignedTo = userRepository.findById(userId)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND,
                    "User not found"));

        alert.setStatus(AlertStatus.IN_PROGRESS);
        alert.setAssignedToUser(assignedTo);
        alert.setAssignedAt(LocalDateTime.now());
        alert.setRead(true);

        alertRepository.save(alert);
        log.debug("[CaregiverAlertService] Alert {} marked as IN_PROGRESS and assigned to user {}",
            alertId, userId);
    }

    /**
     * Résout une alerte avec note clinique optionnelle
     * 
     * @param alertId ID de l'alerte
     * @param userId ID de l'utilisateur qui résout
     * @param userRole Rôle
     * @param clinicalNote Note optionnelle
     * @throws ResponseStatusException si alerte pas trouvée (404) ou accès refusé (403)
     */
    public void resolveAlert(Long alertId, Long userId, String userRole, String clinicalNote) {
        log.info("[CaregiverAlertService] Resolving alert {} by {} ({})",
                alertId, userId, userRole);

        Alert alert = alertRepository.findById(alertId)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND,
                    "Alert not found"));

        // Vérifier les droits d'accès
        if ("CAREGIVER".equalsIgnoreCase(userRole)) {
            verifyAccessToPatient(userId, alert.getPatient().getId());
        }

        // Mettre à jour
        User resolvedBy = userRepository.findById(userId)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND,
                    "User not found"));

        alert.setStatus(AlertStatus.RESOLVED);
        alert.setResolvedByUser(resolvedBy);
        alert.setResolvedAt(LocalDateTime.now());
        alert.setRead(true);

        if (clinicalNote != null && !clinicalNote.isBlank()) {
            alert.setClinicalNote(clinicalNote);
        }

        alertRepository.save(alert);
        log.debug("[CaregiverAlertService] Alert {} resolved by user {}", alertId, userId);
    }

    /**
     * Ajoute une note clinique à une alerte
     * 
     * @param alertId ID de l'alerte
     * @param note Note à ajouter
     * @param userId ID de l'utilisateur
     * @param userRole Rôle
     * @throws ResponseStatusException si alerte pas trouvée (404) ou accès refusé (403)
     */
    public void addClinicalNote(Long alertId, String note, Long userId, String userRole) {
        log.info("[CaregiverAlertService] Adding clinical note to alert {} by {} ({})",
                alertId, userId, userRole);

        if (note == null || note.isBlank()) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST,
                "Clinical note cannot be empty");
        }

        Alert alert = alertRepository.findById(alertId)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND,
                    "Alert not found"));

        // Vérifier les droits d'accès
        if ("CAREGIVER".equalsIgnoreCase(userRole)) {
            verifyAccessToPatient(userId, alert.getPatient().getId());
        }

        // Ajouter la note avec timestamp et auteur
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND,
                    "User not found"));

        String enrichedNote = String.format("[%s - %s at %s]: %s",
                userRole,
                user.getNom() + " " + user.getPrenom(),
                LocalDateTime.now(),
                note);

        String currentNote = alert.getClinicalNote();
        if (currentNote != null && !currentNote.isBlank()) {
            alert.setClinicalNote(currentNote + "\n" + enrichedNote);
        } else {
            alert.setClinicalNote(enrichedNote);
        }

        alertRepository.save(alert);
        log.debug("[CaregiverAlertService] Clinical note added to alert {}", alertId);
    }

    /**
     * Récupère TOUTES les alertes de TOUS les patients d'un caregiver
     * 
     * @param caregiverId ID du caregiver
     * @return Liste de toutes les alertes regroupées par patient, triées par date décroissante
     */
    @Transactional(readOnly = true)
    public List<AlertResponseDTO> getAlertsForAllCaregiverPatients(Long caregiverId) {
        log.info("[CaregiverAlertService] Getting all alerts for all patients of caregiver {}", caregiverId);

        // Récupérer tous les liens du caregiver
        List<CaregiverLink> links = caregiverLinkRepository.findByCaregiverId(caregiverId);

        if (links.isEmpty()) {
            log.info("[CaregiverAlertService] Caregiver {} has no linked patients", caregiverId);
            return List.of();
        }

        // Récupérer tous les IDs des patients
        List<Long> patientIds = links.stream()
                .map(link -> link.getPatient().getId())
                .toList();

        log.info("[CaregiverAlertService] Found {} patients linked to caregiver {}", 
            patientIds.size(), caregiverId);

        // Récupérer toutes les alertes pour ces patients
        List<Alert> alerts = alertRepository.findByPatientIdInOrderByCreatedAtDesc(patientIds);

        log.info("[CaregiverAlertService] Found {} total alerts for caregiver {}", 
            alerts.size(), caregiverId);

        return alerts.stream()
                .map(this::mapToResponseDTO)
                .toList();
    }

    // ==================== HELPER METHODS ====================

    /**
     * Vérifie qu'un caregiver est bien lié au patient
     * 
     * @param caregiverId ID du caregiver
     * @param patientId ID du patient
     * @throws ResponseStatusException (403 Forbidden) si pas lié
     */
    private void verifyAccessToPatient(Long caregiverId, Long patientId) {
        log.debug("[CaregiverAlertService] Verifying access: caregiver {} to patient {}",
            caregiverId, patientId);

        Optional<CaregiverLink> link = caregiverLinkRepository
                .findByCaregiverIdAndPatientId(caregiverId, patientId);

        if (link.isEmpty()) {
            log.warn("[CaregiverAlertService] Unauthorized access attempt: caregiver {} trying to access patient {}",
                caregiverId, patientId);
            throw new ResponseStatusException(HttpStatus.FORBIDDEN,
                "You are not linked to this patient");
        }
    }

    /**
     * Calcule le score de gravité (0-100) d'une alerte basé sur sa sévérité
     * 
     * @param alert L'alerte à évaluer
     * @return Score entre 0 et 100
     */
    private Integer calculateGravityScore(Alert alert) {
        return switch (alert.getSeverity()) {
            case CRITICAL, CRITIQUE -> 90;  // Legacy French value
            case HIGH, ELEVE -> 70;          // Legacy French value
            case MEDIUM, MOYEN -> 50;        // Legacy French value
            case LOW, FAIBLE -> 20;          // Legacy French value
        };
    }

    /**
     * Mappe une entité Alert à un DTO AlertResponseDTO
     * Récupère tous les détails nécessaires y compris le rôle du créateur
     */
    private AlertResponseDTO mapToResponseDTO(Alert alert) {
        AlertResponseDTO.AlertResponseDTOBuilder builder = AlertResponseDTO.builder()
                .id(alert.getId())
                .patientId(alert.getPatient().getId())
                .patientName(alert.getPatient().getUser().getNom() + " " + alert.getPatient().getUser().getPrenom())
                .type(alert.getType().name())
                .title(alert.getTitle())
                .description(alert.getDescription())
                .severity(alert.getSeverity().name())
                .status(alert.getStatus().name())
                .gravityScore(alert.getGravityScore())
                .isRead(alert.isRead())
                .isEscalated(alert.isEscalated())
                .isAutoGenerated(alert.isAutoGenerated())
                .linkedReminderId(alert.getLinkedReminderId())
                .clinicalNote(alert.getClinicalNote())
                .sourceKey(alert.getSourceKey())
                .createdAt(alert.getCreatedAt())
                .assignedAt(alert.getAssignedAt())
                .resolvedAt(alert.getResolvedAt())
                .updatedAt(alert.getUpdatedAt());

        // Informations de création
        if (alert.getCreatedBy() != null) {
            builder.createdById(alert.getCreatedBy().getId())
                    .createdByName(alert.getCreatedBy().getNom() + " " + alert.getCreatedBy().getPrenom())
                    .createdByRole(alert.getCreatedBy().getRole());
        }

        // Informations d'assignation
        if (alert.getAssignedToUser() != null) {
            builder.assignedToUserId(alert.getAssignedToUser().getId())
                    .assignedToUserName(alert.getAssignedToUser().getNom() + " " + alert.getAssignedToUser().getPrenom());
        }

        // Informations de résolution
        if (alert.getResolvedByUser() != null) {
            builder.resolvedById(alert.getResolvedByUser().getId())
                    .resolvedByName(alert.getResolvedByUser().getNom() + " " + alert.getResolvedByUser().getPrenom());
        }

        return builder.build();
    }
}
