export type AlertRole = 'DOCTOR' | 'CAREGIVER' | 'PATIENT';

export type AlertType =
  | 'MEDICATION_MISSED'
  | 'COGNITIVE_DECLINE'
  | 'CAREGIVER_BURNOUT'
  | 'SAFETY'
  | 'REMINDER_DELAY'
  | 'REMINDER_MISSED'
  | 'WELLBEING'
  | 'WEATHER'
  | 'MANUAL';

export type AlertStatus = 'UNREAD' | 'IN_PROGRESS' | 'RESOLVED';

export type AlertSeverity = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

export type AlertFilter = 'ALL' | 'UNREAD' | 'IN_PROGRESS' | 'RESOLVED';

export interface Alert {
  id: number;
  patientId: number;
  patientName: string;
  title: string;
  description: string;
  type: AlertType;
  status: AlertStatus;
  severity: AlertSeverity;
  createdAt: string;
  resolvedAt?: string;
  read: boolean;
  createdById?: number;
  createdByName?: string;
  createdBy?: AlertRole; // Who created the alert (for manual alerts)
  reminderId?: number;
  autoGenerated?: boolean;
  isManual?: boolean; // True if manually created by caregiver/doctor
  notes?: string; // Internal notes about the alert
}

export interface CreateAlertRequest {
  title: string;
  description: string;
  type: AlertType;
  severity: AlertSeverity;
  patientId?: number;
}

export interface WeeklyEvolutionPoint {
  label: string;
  count: number;
}

export interface TopAlertTypeItem {
  type: AlertType;
  count: number;
}

export interface PatientTrendPoint {
  month: string;
  alertsCount: number;
  observanceRate: number;
}

export interface AlertDashboard {
  patientId: number;
  patientName: string;
  weeklyEvolution: WeeklyEvolutionPoint[];
  topTypes: TopAlertTypeItem[];
  resolutionRate: number;
  patientTrends: PatientTrendPoint[];
}

export interface ChatMessage {
  patientId: number;
  senderUserId: number;
  senderRole: AlertRole;
  senderName: string;
  content: string;
  sentAt: string;
}

export interface SendChatMessageRequest {
  patientId: number;
  content: string;
  senderRole?: 'DOCTOR' | 'CAREGIVER';
}

/**
 * KPI Dashboard pour l'accompagnant: statistiques clés de la journée
 */
export interface CaregiverDashboardKpi {
  patientId: number;
  todayAlertsCount: number;
  criticalUnresolvedCount: number;
  weeklyReminderConfirmationRate: number;
  globalRiskScore: number; // 0-100, composé de multiples facteurs
  lastAlertAt?: string;
}

/**
 * Résumé IA/journal de la journée pour un patient spécifique
 */
export interface DayAiSummary {
  patientId: number;
  summary: string; // Texte généré
  generatedAt: string;
  keyInsights: string[];
  recommendations: string[];
}

/**
 * Événement temporel pour la timeline visuelle
 */
export interface DayTimelineEvent {
  time: string; // HH:mm format
  type: AlertType | string;
  status: AlertStatus;
  title: string;
  severity: AlertSeverity;
}

/**
 * Timeline simplifiée de la journée
 */
export interface DayTimeline {
  patientId: number;
  date: string;
  events: DayTimelineEvent[];
}

export type WeatherDangerLevel = 'LOW' | 'MEDIUM' | 'HIGH';

export interface WeatherCurrent {
  temperature: number;
  condition: string;
  description: string;
  icon: string;
  dangerLevel: WeatherDangerLevel;
  updatedAt: string;
  humidity?: number;
  windSpeed?: number;
}
